version: '3.5'

services:

  er:
    container_name: er
    image: nginx
    labels:
      - "traefik.enable=true"
      - "traefik.backend.port=80"
      - "traefik.frontend.rule=Host:www.espace-revendeurs.ign.fr"
    volumes:
      - .:/usr/share/nginx/html:ro
    restart: unless-stopped

networks:
  default:
    external:
      name: webgateway

